service: abc-farms-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    EVENT_BUS_NAME: !Ref EventBus
    PRODUCTS_TABLE_NAME: !Ref productsTable
    ORDERS_TABLE_NAME: !Ref ordersTable

functions: ${file(configs/functions.yml)}
  
plugins:
  - serverless-plugin-typescript
  - serverless-iam-roles-per-function

resources:
  Resources: ${file(configs/resources.yml)}
  Outputs:
    EventBusName:
      Value: !Ref EventBus
    