# Tables
productsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: products-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST 
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
ordersTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: orders-${self:provider.stage}
    BillingMode: PAY_PER_REQUEST 
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH

# Eventbridge
EventBus:
  Type: AWS::Events::EventBus
  Properties:
    Name: ORDER_CREATED_EVENT_BUS